gateway:
  security:
    public-paths:
      - "/api/v1/auth/login"
      - "/api/v1/auth/register"
      - "/api/v1/auth/refresh"
      - "/eureka"

spring:
  cloud:
    gateway:
      routes:
        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: JwtAuthenticationFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@userKeyResolver}"
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback/auth
                statusCodes:
                  - 502
                  - 503
                  - 504

        - id: ms-social
          uri: lb://ms-social
          predicates:
            - Path=/api/v1/creators/**
          filters:
            - name: JwtAuthenticationFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@userKeyResolver}"

        - id: ms-creation
          uri: lb://ms-creation
          predicates:
            - Path=/api/v1/creation/outfits/**
            - Path=/api/v1/creation/items/**
          filters:
            - name: JwtAuthenticationFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@userKeyResolver}"

        - id: ms-feed
          uri: lb://ms-feed
          predicates:
            - Path=/api/v1/outfits/**
          filters:
            - name: JwtAuthenticationFilter
